;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        handle-switch-frame
        ignore-preserving-kill-region
        indent-for-tab-command
        keyboard-escape-quit
        lsp-ui-doc--handle-mouse-movement
        overwrite-mode
        ))

(setq mc/cmds-to-run-once
      '(
        mouse-set-region
        ))
