;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        handle-switch-frame
        ignore-preserving-kill-region
        indent-for-tab-command
        keyboard-escape-quit
        kill-region
        lsp-format-buffer
        lsp-ui-doc--handle-mouse-movement
        mark-word
        multiple-cursors-mode
        overwrite-mode
        switch-to-buffer
        undo-redo
        ))

(setq mc/cmds-to-run-once
      '(
        mouse-set-region
        ))
