;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        corfu-insert
        handle-switch-frame
        ignore-preserving-kill-region
        keyboard-escape-quit
        lsp-ui-doc--handle-mouse-movement
        ))

(setq mc/cmds-to-run-once
      '(
        ))
